language: java
services: postgresql
addons: 
  postgresql:"9.3"
before_script:
  - psql -c 'create database sc_lint_test;' -U postgres
cache:
  directories:
  - .autoconf
  - $HOME/.m2
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
