language: java
jdk:
  - oraclejdk8
services: postgresql
addons: 
  postgresql:"9.3"
before_script:
  - dropdb --if-exists sc_lint_test
  - psql -c 'create database sc_lint_test;' -U postgres
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
