language: java
env:
  global:
  - secure: "T2/6RAFbkIdMtoR93n8EtyVH04VZ513RhE0p+mdwUIXmIEHye60jFWOPin3arokYBTY/NQvU5Mnt1aNKcsqBt/6hbkrr1PBEWooJ5/ZFIbMnGCSs8AJvqlCRE0doSJFuh+fxoitJ0a0gn9Xi5UZ6IrO22ZftmaTRbepC1lmYvvyn7ppeqD6AULn7+5P50A7OoV9tx2/yXJhFnUgkHKs9kMMhGjU2wCkAf4cXCcdWk+zSXr6na7rkLmFZncz40zCZVS/b6tBm9yahgYth5nBJ9OsQLviWb9yUxvTWvwAFIU1+uezD0u8XtzVvZU4PkaVwHM5OmtnN6fuJjmsAufRlFb9Vom0O6gY5QtiPN7KsrqNAxaI0/MLDAPDtChHnL9TEFGJHBuFpCUXnOdNcRy+L/TSLd3JBb3PZJFvkgk8l/+5t3mcFjgThK7dkxs+209SdEAQh5kw5bTdhizVJrDaEEHo1zBU51RVKEy62Fo+YZ4Fb2n9EQottEfCH56evJkExM1kQPOzCRqafWUm1JXv7gSbtVSV/WYvgeisUVCCCkE9O24hJcns18fQXxvHB16cf8lMxCZ9PTQZWiDNO7pto0dNbpiXqiMlwrohamVTVEKj8af7MQmEzr131so6Y7CE8WyIXGw206RsROusZcIjumHTgC4L8EO4Puig41SxGvcA="
services: postgresql
addons: 
  postgresql:"9.3"
before_script:
  - psql -c 'create database sc_lint_test;' -U postgres
cache:
  directories:
  - .autoconf
  - $HOME/.m2
after_success:
  - mvn clean -DrepoToken=$REPO_TOKEN cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
